import {
	copyFileSync,
	existsSync,
	mkdirSync,
	readFileSync,
	writeFileSync,
} from "node:fs";
import { builtinModules } from "node:module";
import process from "node:process";
import esbuild from "esbuild";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const outdir = prod ? "build" : ".";

/**
 * Stamp the source manifest with a dev-suffixed version for the test vault
 * so every build looks like a fresh version to Obsidian's plugin loader —
 * defeats stale-module caching during manual QA. Source manifest.json is
 * NEVER modified; the canonical version stays the GitHub release version.
 *
 * Format mirrors miyo-archivist + miyo-tomo-hashi:
 * `${baseVersion}-dev.${YYYYMMDD-HHmm}`, e.g. "0.0.0-dev.20260428-1620".
 * The `-dev.` is a semver pre-release identifier so it sorts BELOW the
 * canonical version — Obsidian and the Community Plugins manifest stay clean.
 */
function stampManifestForVault() {
	const manifest = JSON.parse(readFileSync("manifest.json", "utf8"));
	const baseVersion = manifest.version;
	const stamp = new Date()
		.toISOString()
		.slice(0, 16)
		.replace(/[-:]/g, "")
		.replace("T", "-");
	manifest.version = `${baseVersion}-dev.${stamp}`;
	return manifest;
}

// Build-time file shuffling. Two independent destinations:
//   - build/        — populated only on prod runs; used for GitHub releases.
//   - test vault    — populated whenever DEPLOY_VAULT=1, in BOTH dev (watch)
//                     and prod modes. The vault path is symlinked / treated as
//                     a community-plugins install dir, so each rebuild fires
//                     pjeby/hot-reload and the plugin live-reloads.
//
// Decoupling deploy from prod lets `npm run dev:vault` watch + auto-deploy
// without forcing a minified release build on every keystroke.
const VAULT_PLUGIN_DIR = "test/Hakobi/.obsidian/plugins/miyo-hakobi";

// Note: assets/hakobi_hanko_144.png is NOT copied alongside main.js — it is
// inlined into main.js by the `loader: { '.png': 'dataurl' }` setting below.
// BRAT (`src/features/BetaPlugins.ts:31-35`) and the official Obsidian
// Community Plugins installer only fetch main.js, manifest.json, and
// styles.css, so any sibling asset would 404 on non-developer installs.
const copyAssets = {
	name: "copy-assets",
	setup(build) {
		build.onEnd(() => {
			if (prod) {
				mkdirSync("build", { recursive: true });
				copyFileSync("manifest.json", "build/manifest.json");
				copyFileSync("styles.css", "build/styles.css");
			}

			if (!process.env.DEPLOY_VAULT) return;

			if (!existsSync("test/Hakobi/.obsidian")) {
				console.warn(
					"[deploy] DEPLOY_VAULT set but test/Hakobi/.obsidian missing — skipped",
				);
				return;
			}

			mkdirSync(VAULT_PLUGIN_DIR, { recursive: true });
			copyFileSync(`${outdir}/main.js`, `${VAULT_PLUGIN_DIR}/main.js`);
			copyFileSync("styles.css", `${VAULT_PLUGIN_DIR}/styles.css`);
			const stampedManifest = stampManifestForVault();
			writeFileSync(
				`${VAULT_PLUGIN_DIR}/manifest.json`,
				JSON.stringify(stampedManifest, null, "\t") + "\n",
				"utf8",
			);
			console.log(
				`[deploy] Plugin copied to ${VAULT_PLUGIN_DIR} (version: ${stampedManifest.version})`,
			);
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
		...builtinModules.map((m) => `node:${m}`),
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: `${outdir}/main.js`,
	minify: prod,
	// Inline binary assets (the plugin hanko) as data URIs so the bundle is
	// fully self-contained — see the comment on `copyAssets` above for why.
	loader: { ".png": "dataurl" },
	plugins: [copyAssets],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
